/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  NEURAL DAY TRADER - PARTNERS MODULE                              ║
 * ║  Partners Database                                                ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 */

import { Partner } from './types';

export const PARTNERS_DATABASE: Partner[] = [
  // BROKERS
  {
    id: 'ic-markets',
    name: 'IC Markets',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400',
    description: 'Líder global em Forex e CFDs com spreads ultra-baixos e execução ECN. Regulado pela ASIC, CySEC e FSA. Spreads a partir de 0.0 pips.',
    category: 'broker',
    tier: 'platinum',
    website: 'https://icmarkets.com',
    benefits: [
      'Spreads a partir de 0.0 pips',
      'Execução ECN em 40ms',
      'Alavancagem até 1:500',
      'Mais de 232 instrumentos',
      'Regulado ASIC, CySEC, FSA',
      'Suporte MetaTrader 5',
    ],
    specialOffer: 'Depósito mínimo reduzido para $50',
    discount: '20% cashback no primeiro mês',
    rating: 4.8,
    usersCount: 180000,
    established: 2007,
    locations: ['Austrália', 'Chipre', 'Seychelles'],
    verified: true,
    featured: true,
  },
  
  {
    id: 'pepperstone',
    name: 'Pepperstone',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400',
    description: 'Broker australiano multi-premiado com tecnologia de ponta e preços competitivos. Ideal para traders algorítmicos.',
    category: 'broker',
    tier: 'platinum',
    website: 'https://pepperstone.com',
    benefits: [
      'Spreads competitivos',
      'API para trading algorítmico',
      'Copy trading integrado',
      '1,200+ instrumentos',
      'Regulado FCA, ASIC, CMA',
      'Suporte MT4/MT5/cTrader',
    ],
    specialOffer: 'Bônus de $50 no primeiro depósito',
    rating: 4.7,
    usersCount: 250000,
    established: 2010,
    locations: ['Austrália', 'Reino Unido', 'Dubai'],
    verified: true,
    featured: true,
  },

  {
    id: 'exness',
    name: 'Exness',
    logo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    description: 'Broker global com execução instantânea e retiradas rápidas. Especializado em contas de alto volume.',
    category: 'broker',
    tier: 'gold',
    website: 'https://exness.com',
    benefits: [
      'Retiradas instantâneas',
      'Sem limite de alavancagem',
      'Spreads estáveis',
      'Volume mensal $3T+',
      'Regulado FCA, CySEC',
      'Suporte 24/7 multilíngue',
    ],
    specialOffer: 'Conta demo ilimitada + curso gratuito',
    rating: 4.6,
    usersCount: 320000,
    established: 2008,
    locations: ['Chipre', 'Reino Unido', 'África do Sul'],
    verified: true,
    featured: false,
  },

  // PROP FIRMS
  {
    id: 'ftmo',
    name: 'FTMO',
    logo: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400',
    description: 'Prop Trading Firm líder com contas de até $400,000. Processo de avaliação transparente e pagamentos rápidos.',
    category: 'prop-firm',
    tier: 'platinum',
    website: 'https://ftmo.com',
    benefits: [
      'Contas até $400,000',
      'Profit split 80/20',
      'Scaling plan automático',
      'Retiradas a cada 14 dias',
      'Sem limites de estratégia',
      'Suporte educacional completo',
    ],
    specialOffer: 'Desconto de 10% no Challenge',
    discount: '10% OFF no primeiro Challenge',
    rating: 4.9,
    usersCount: 50000,
    established: 2015,
    locations: ['República Tcheca'],
    verified: true,
    featured: true,
  },

  {
    id: 'the5ers',
    name: 'The5%ers',
    logo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400',
    description: 'Prop Firm inovadora com programa de financiamento imediato. Foco em desenvolvimento de traders.',
    category: 'prop-firm',
    tier: 'gold',
    website: 'https://the5ers.com',
    benefits: [
      'Programa de funding instantâneo',
      'Contas até $250,000',
      'Sem avaliação (Boot Camp)',
      'Profit split até 100%',
      'Sem tempo limite',
      'Mentoria inclusa',
    ],
    specialOffer: 'Boot Camp com 50% de desconto',
    discount: '50% OFF no Boot Camp',
    rating: 4.7,
    usersCount: 25000,
    established: 2016,
    locations: ['Israel', 'Chipre'],
    verified: true,
    featured: true,
  },

  {
    id: 'topstep',
    name: 'TopStep',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400',
    description: 'Líder em Prop Trading de Futuros. Mais de $150M pagos aos traders. Foco em traders disciplinados.',
    category: 'prop-firm',
    tier: 'gold',
    website: 'https://topstep.com',
    benefits: [
      'Especializado em Futuros',
      'Contas até $150,000',
      'Profit split 80/20',
      '$150M+ pagos aos traders',
      'Simulador realista',
      'Comunidade ativa',
    ],
    specialOffer: 'Reset gratuito no primeiro Challenge',
    rating: 4.5,
    usersCount: 35000,
    established: 2012,
    locations: ['Estados Unidos'],
    verified: true,
    featured: false,
  },

  // DATA PROVIDERS
  {
    id: 'tradingview',
    name: 'TradingView',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    description: 'Plataforma de charting mais popular do mundo. Dados em tempo real de 100+ exchanges.',
    category: 'data-provider',
    tier: 'platinum',
    website: 'https://tradingview.com',
    benefits: [
      'Dados de 100+ exchanges',
      'Charting profissional',
      'Social trading integrado',
      'Alertas customizáveis',
      'API de dados',
      'Scanner de mercado',
    ],
    specialOffer: 'Premium com 60% de desconto',
    discount: '60% OFF no plano anual',
    rating: 4.9,
    usersCount: 50000000,
    established: 2011,
    locations: ['Estados Unidos'],
    verified: true,
    featured: true,
  },

  {
    id: 'polygon-io',
    name: 'Polygon.io',
    logo: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400',
    description: 'API de dados financeiros em tempo real. Cobertura completa de ações, opções, forex e cripto.',
    category: 'data-provider',
    tier: 'gold',
    website: 'https://polygon.io',
    benefits: [
      'WebSocket real-time',
      'Dados históricos completos',
      'Latência < 10ms',
      'RESTful API',
      'Dados de opções',
      'Suporte técnico premium',
    ],
    specialOffer: 'API gratuita para Neural Traders',
    rating: 4.6,
    usersCount: 15000,
    established: 2016,
    locations: ['Estados Unidos'],
    verified: true,
    featured: false,
  },

  // EXCHANGES
  {
    id: 'binance',
    name: 'Binance',
    logo: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=400',
    description: 'Maior exchange de criptomoedas do mundo. Volume diário de $30B+. Mais de 350 criptomoedas.',
    category: 'exchange',
    tier: 'platinum',
    website: 'https://binance.com',
    benefits: [
      'Maior liquidez do mercado',
      'Taxas competitivas (0.1%)',
      '350+ criptomoedas',
      'API robusta',
      'Staking e Lending',
      'Segurança multi-camada',
    ],
    specialOffer: 'Taxa reduzida para Neural Traders',
    discount: '20% de desconto nas taxas',
    rating: 4.7,
    usersCount: 120000000,
    established: 2017,
    locations: ['Global'],
    verified: true,
    featured: true,
  },

  {
    id: 'coinbase',
    name: 'Coinbase Pro',
    logo: 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=400',
    description: 'Exchange regulada nos EUA com foco em segurança e conformidade. Ideal para traders institucionais.',
    category: 'exchange',
    tier: 'gold',
    website: 'https://pro.coinbase.com',
    benefits: [
      'Regulado nos EUA',
      'Seguro pela FDIC',
      'API profissional',
      'Custody institucional',
      'Suporte 24/7',
      'Liquidez profunda',
    ],
    specialOffer: 'Onboarding premium para clientes Neural',
    rating: 4.5,
    usersCount: 100000000,
    established: 2012,
    locations: ['Estados Unidos'],
    verified: true,
    featured: false,
  },

  // EDUCATION
  {
    id: 'babypips',
    name: 'BabyPips',
    logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400',
    description: 'Escola online gratuita de Forex. Mais de 3 milhões de traders treinados. Conteúdo de qualidade.',
    category: 'education',
    tier: 'silver',
    website: 'https://babypips.com',
    benefits: [
      'Curso gratuito completo',
      'Comunidade ativa',
      'Fórum de discussão',
      'Análises diárias',
      'Tools gratuitos',
      'Glossário completo',
    ],
    specialOffer: 'Acesso VIP gratuito por 3 meses',
    rating: 4.8,
    usersCount: 3000000,
    established: 2005,
    locations: ['Online'],
    verified: true,
    featured: false,
  },

  // TECHNOLOGY
  {
    id: 'metaapi',
    name: 'MetaAPI',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    description: 'Cloud API para MetaTrader 4/5. Integração perfeita com a Neural Day Trader Platform.',
    category: 'technology',
    tier: 'platinum',
    website: 'https://metaapi.cloud',
    benefits: [
      'API Cloud MT4/MT5',
      'WebSocket real-time',
      'Latência ultra-baixa',
      'Histórico completo',
      'Backtesting na nuvem',
      'Integração com 1200+ brokers',
    ],
    specialOffer: 'Parceiro oficial - API integrada',
    rating: 4.9,
    usersCount: 8000,
    established: 2019,
    locations: ['Global'],
    verified: true,
    featured: true,
  },
];

export function getPartnersByCategory(category: string) {
  return PARTNERS_DATABASE.filter(p => p.category === category);
}

export function getFeaturedPartners() {
  return PARTNERS_DATABASE.filter(p => p.featured);
}

export function getPartnerById(id: string) {
  return PARTNERS_DATABASE.find(p => p.id === id);
}
