/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  NEURAL DAY TRADER - MARKETPLACE                                  ║
 * ║  Exclusive Products Catalog                                       ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 */

import { Product } from './types';

export const MARKETPLACE_PRODUCTS: Product[] = [
  // PRODUTO 1: GERENCIADOR DE RISCO NEURAL (PRODUTO PRÓPRIO)
  {
    id: 'ndt-risk-manager',
    name: 'Neural Risk Manager Pro',
    tagline: 'Gerenciamento de Risco Baseado em IA - Proteja Seu Capital',
    description: 'Sistema avançado de gerenciamento de risco que utiliza redes neurais para calcular automaticamente o tamanho ideal de posição, stop loss dinâmico, e gestão de drawdown. Integrado diretamente na Neural Day Trader Platform com análise em tempo real de 300+ ativos.',
    price: 297,
    originalPrice: 497,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    badge: 'exclusive',
    features: [
      '🧠 IA calcula tamanho de posição baseado em volatilidade',
      '🎯 Stop Loss e Take Profit dinâmicos',
      '📊 Análise de correlação entre ativos',
      '⚡ Alertas de risco em tempo real',
      '📈 Máximo drawdown configurável',
      '🔄 Rebalanceamento automático de portfólio',
    ],
    benefits: [
      'Reduza perdas em até 73%',
      'Aumente consistência dos resultados',
      'Elimine decisões emocionais',
      'Proteja seu capital automaticamente',
    ],
    included: [
      'Acesso vitalício ao Neural Risk Manager',
      'Integração completa com MetaTrader 5',
      'Suporte prioritário 24/7',
      'Atualizações gratuitas',
      'Curso: "Gestão de Risco Avançada" ($199)',
      'Templates pré-configurados',
    ],
    rating: 4.9,
    reviews: 1247,
    sales: 3891,
    category: 'risk-management',
    type: 'lifetime',
    isOwnProduct: true,
  },

  // PRODUTO 2: WHALE ALERT SYSTEM
  {
    id: 'whale-alert-pro',
    name: 'Whale Alert Intelligence',
    tagline: 'Rastreie Movimentos de Baleias em Tempo Real',
    description: 'Sistema exclusivo que detecta e alerta sobre grandes movimentações de capital (baleias) em Forex, Cripto e Índices. Receba notificações instantâneas quando grandes players entrarem ou saírem de posições, permitindo que você siga o dinheiro inteligente.',
    price: 147,
    originalPrice: 247,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800',
    badge: 'best-seller',
    features: [
      '🐋 Detecta movimentações acima de $10M',
      '⚡ Alertas instantâneos (Telegram + Email + App)',
      '🌍 Cobertura: Forex, Cripto, Índices, Commodities',
      '📊 Heatmap de liquidez institucional',
      '🔍 Análise de order flow em tempo real',
      '📈 Histórico de 2 anos de movimentações',
    ],
    benefits: [
      'Antecipe grandes movimentos de mercado',
      'Siga o dinheiro institucional',
      'Entre antes da multidão',
      'Evite armadilhas de liquidez',
    ],
    included: [
      'Assinatura de 1 ano',
      'Alertas ilimitados',
      'Acesso ao Whale Dashboard',
      'API de integração',
      'Grupo VIP no Telegram',
    ],
    rating: 4.8,
    reviews: 892,
    sales: 2456,
    category: 'analytics',
    type: 'subscription',
  },

  // PRODUTO 3: SENTIMENT SCANNER AI
  {
    id: 'sentiment-scanner',
    name: 'Market Sentiment Scanner AI',
    tagline: 'Análise de Sentimento de Mercado com Deep Learning',
    description: 'IA que analisa 500.000+ posts diários de Twitter, Reddit, Telegram e fóruns especializados para detectar mudanças de sentimento antes que impactem os preços. Utiliza NLP (Natural Language Processing) e análise de emoções para prever movimentos.',
    price: 197,
    originalPrice: 347,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    badge: 'new',
    features: [
      '🤖 Análise de 500k+ posts diários',
      '📱 Fontes: Twitter, Reddit, Telegram, StockTwits',
      '🎯 Score de sentimento (0-100) por ativo',
      '🔥 Detecta "hype" e FUD antes da multidão',
      '📊 Dashboard visual com tendências',
      '⏰ Alertas de mudança de sentimento',
    ],
    benefits: [
      'Antecipe movimentos de 6-24h',
      'Detecte manipulação de mercado',
      'Encontre oportunidades antes dos outros',
      'Evite armadilhas emocionais',
    ],
    included: [
      'Assinatura mensal',
      'Análise de 100+ ativos',
      'Relatórios diários por email',
      'API REST para integração',
      'Extensão Chrome',
    ],
    rating: 4.7,
    reviews: 634,
    sales: 1823,
    category: 'ai-tools',
    type: 'subscription',
  },

  // PRODUTO 4: COPY TRADER NEURAL
  {
    id: 'copy-trader-neural',
    name: 'Neural Copy Trading Engine',
    tagline: 'Copie Automaticamente os Melhores Traders do Mundo',
    description: 'Sistema revolucionário que utiliza IA para analisar milhares de traders profissionais, selecionar os melhores baseado em 47 métricas de desempenho, e copiar suas operações automaticamente na sua conta. A IA aprende e otimiza continuamente a seleção.',
    price: 397,
    originalPrice: 697,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800',
    badge: 'premium',
    features: [
      '🏆 Acesso a 5.000+ traders verificados',
      '🤖 IA seleciona traders baseado em 47 métricas',
      '📊 Ranking dinâmico (atualizado a cada 1h)',
      '⚙️ Ajuste automático de risco',
      '🔄 Rebalanceamento inteligente',
      '📈 Performance tracking detalhado',
    ],
    benefits: [
      'Lucre mesmo sem experiência',
      'Diversificação automática',
      'Sem necessidade de análise técnica',
      'Sistema 100% hands-free',
    ],
    included: [
      'Licença vitalícia',
      'Cópia de até 10 traders simultâneos',
      'Relatórios semanais de performance',
      'Suporte prioritário',
      'Configuração personalizada',
      'Backtest histórico ilimitado',
    ],
    rating: 4.9,
    reviews: 1523,
    sales: 4192,
    category: 'automation',
    type: 'lifetime',
  },

  // PRODUTO 5: QUANTUM STRATEGY BUILDER
  {
    id: 'quantum-strategy',
    name: 'Quantum Strategy Builder',
    tagline: 'Crie Estratégias Vencedoras com Algoritmos Genéticos',
    description: 'Ferramenta única que utiliza algoritmos genéticos e otimização quântica para criar, testar e evoluir estratégias de trading automaticamente. O sistema testa milhões de combinações e "evolui" as estratégias mais lucrativas através de gerações.',
    price: 497,
    originalPrice: 897,
    currency: 'USD',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
    badge: 'best-seller',
    features: [
      '🧬 Algoritmos genéticos para evolução de estratégias',
      '⚛️ Otimização quântica de parâmetros',
      '🔬 Backtesting em 20+ anos de dados',
      '🎯 Walk-forward analysis automático',
      '📊 Monte Carlo simulation (10.000+ cenários)',
      '🤖 Auto-deploy em MetaTrader 5',
    ],
    benefits: [
      'Encontre estratégias únicas e lucrativas',
      'Elimine overfitting',
      'Teste milhões de combinações em minutos',
      'Estratégias que se adaptam ao mercado',
    ],
    included: [
      'Licença vitalícia',
      'Biblioteca com 500+ estratégias base',
      'Acesso a cluster de processamento',
      'Curso: "Algoritmos Genéticos para Trading"',
      'Suporte técnico especializado',
      'Export para Python/MQL5',
    ],
    rating: 4.8,
    reviews: 743,
    sales: 2891,
    category: 'ai-tools',
    type: 'lifetime',
  },
];
